src/blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view
)

app_name ='blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 


from personal.views import (
    home_screen_view,
    
)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),    
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    #path('account/', include('django.contrib.auth.urls')), #la forma predeterminada que tiene djanfo para hacer el cambio de password pero interfiere con mi plantilla
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# Create your models here.
# PRIORITY = [ 
#     ("L", "Low"), 
#     ("M", "Mediun"), 
#     ("H", "High"), 
# ] 


# class Question(models.Model):
#     title 					= models.CharField(max_length=70)
#     question				= models.TextField(max_length=400)
#     priority 				= models.CharField(max_length=1, choices=PRIORITY)

#     class Meta:
#      	verbose_name = "The Question"
#      	verbose_name_plural = "Peoples Questions"

#     def __str__(self):
#         return self.title

# BRAND = [
#  	("Niagara", "Niagara"),
#  	("Phoenix", "Phoenix"),
# 	("Giant", "Giant"),
#  ]

# class Bikes(models.Model):
# 	name 					=models.CharField(max_length=70)
# 	brand					=models.CharField(max_length=20, choices=BRAND)
# 	description				=models.TextField(max_length=400)

# 	class Meta:
# 		verbose_name = "La bicicleta"
# 		verbose_name_plural = "Las Bicicletas"

# 	def __str__(self):
# 		return self.name

src/personal/views.py
from django.shortcuts import render
# from personal.models import Question
# from personal.models import Bikes
from account.models import Account
# Create your views here.

def home_screen_view(request):

     context = {}

     accounts = Account.objects.all()
     context['accounts'] = accounts






     # list_of_values=[]
     # list_of_values.append("first entry")
     # list_of_values.append("second entry")
     # list_of_values.append("third entry")
     # list_of_values.append("fourth entry")
     # context['list_of_values'] = list_of_values

     #context['some_string']="This is some string that Im passing to the view"
     #context['some_number']=860623

    
     # questions = Question.objects.all()
     # context ['questions'] = questions

     # bikes = Bikes.objects.all()
     # context ['bikes'] = bikes


     return render (request, "personal/home.html", context )

src/personal/templates/personal/home.html
{% extends 'base.html'%}


{% block content %}

 <style type="text/css">

  @media (max-width: 768px) {
    .rigth-column{
      margin-left: 0px;
    }
  }

  @media (min-width: 768px) {
    .rigth-column{
      margin-left: 20px;
    }
  }
   .blog-post-container{
    background-color: #fff;
    margin-bottom: 20px;
    width: 100%;
   }
   .create-post-bar{
    background-color: #fff;
    margin-bottom: 20px;
   }
   .left-column{
    padding: 0px;
   }
   .rigth-column{
    padding: 0px;
   }
   </style>

  <div class="container">
  		<div class="row"> 
  			
        <!-- Rigth create post bar -->
        <div class="create-post-bar d-lg-none col-lg-7 offset-lg-1">
          <a href="{%url 'blog:create' %}">Create Post</a>
        </div>

        <!-- end Rigth create post bar -->

        <!-- Blog feed  -->
        <div class="left-column col-lg-7 offset-lg-1">
          
          <div class="blog-post-container">
            <p>Thingy</p>
          </div>

          <div class="blog-post-container">
            <p>Thingy</p>
          </div>

          <div class="blog-post-container">
            <p>Thingy</p>
          </div>

          <div class="blog-post-container">
            <p>Thingy</p>
          </div>

        </div>
        <!-- end Blog feed  -->

        <!-- Rigth create post column -->
        <div class="rigth-column col-lg-3 d-lg-flex d-none flex-column">
          <div class="create-post-bar">
            <p>Stuff</p>  
            <p>Stuff</p>            
            <p>Stuff</p>            
            <p>Stuff</p> 
            <a href="{%url 'blog:create' %}">Create Post</a>           
          </div>
        </div>
        <!-- end Rigth create post column -->

  		</div>
  	
  </div>
  
 

{% endblock content %}