src/blog/urls.py
from django.urls import path
from blog.views import(

	create_blog_view,
	detail_blog_view
)

app_name ='blog'

urlpatterns = [
	path('create/', create_blog_view, name="create"),
	path('<slug>/', detail_blog_view, name="detail"),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 


from personal.views import (
    home_screen_view,
    
)

from account.views import(
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('account/', account_view, name="account"),
    path('blog/', include('blog.urls', 'blog')),    
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    #path('account/', include('django.contrib.auth.urls')), #la forma predeterminada que tiene djanfo para hacer el cambio de password pero interfiere con mi plantilla
    ]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models

# Create your models here.

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver


def upload_location(instance, filename, **kwargs):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
			author_id=str(instance.author.id), title=str(instance.title), filename=filename
				)
	return file_path

class BlogPost(models.Model):
	title 					= models.CharField(max_length=50, null=False, blank=False)
	body 					= models.TextField(max_length=5000, null=False, blank=False)
	image 					= models.ImageField(upload_to=upload_location, null=False, blank=False)
	date_published			= models.DateTimeField(auto_now_add=True, verbose_name="date published")
	date_updated			= models.DateTimeField(auto_now=True, verbose_name="date updated")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	slug 					= models.SlugField(blank=True, unique=True)

	def __str__ (self):
		return self.title

@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
	instance.image.delete()

def pre_save_blog_receiver(sender, instance, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_receiver, sender=BlogPost)

src/blog/forms.py
from django import forms
from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image',]

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

from blog.models import BlogPost
from blog.forms import CreateBlogPostForm
from account.models import Account

def create_blog_view(request):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect ('must_authenticate')

	form = CreateBlogPostForm(request.POST or None, request.FILES or None)
	if form.is_valid():
		obj = form.save(commit=False) #*(commit=false) guarda el formulario despues que los campos ya fueron validados 
		author = Account.objects.filter(email=user.email).first()
		obj.author = author
		obj.save()
		form = CreateBlogPostForm()

	context['form'] = form


	return render (request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):

	context = {}

	blog_post = get_object_or_404(BlogPost, slug=slug)
	context['blog_post'] = blog_post

	return render(request, 'blog/detail_blog.html', context)

src/blog/templates/blog/create_blog.html
{% extends 'base.html'%}


{% block content %}

<style type="text/css">
	
	.create-form{
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
	}
	.submit-button{
		max-width: 200px;

	}


</style>

<div class="container">
	<div class="row">
		<div class="col-lg offset-lg-1">
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
				<!-- Title -->
				<div class="form-group">
					<label for="id_title">Title</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="Title" required autofocus>					
				</div>
				<!-- Body -->
				<div class="form-group">
					<label for="id_body">Content</label>
					<textarea class="form-group" rows="10" type="text" name="body" id="id_body" placeholder="This Blog is about..." required></textarea>
				</div>
				<!-- Image -->
				<div class="form-group">
					<label for="id_image">Image</label>
					<input type="file" name="image" id="id_image" accept="image/*" required >
				</div>

				<!-- Submit -->
				<button class="submit-button btn btn-lg btn-primary btn-lock" type="submit">Post</button>
			</form>
		</div>
	</div>
</div>












{% endblock content %}

src/blog/templates/blog/detail_blog.html
{% extends 'base.html'%}


{% block content %}
<style type="text/css">
	
	.card{
		max-width: 700px;
	}
	.container{
		padding: 20px;
	}
</style>

<div class="container">
	<div class="row">
		<!-- Blog Post -->
			 <div class="card m-auto ">
			 	<img class="img-top" src="{{blog_post.image.url}}">
			 	<div class="card-body mt-2 mb-2">
			 		<h2 class="card-title">{{blog_post.title}}</h2>
			 		<p class="card-text">{{blog_post.body|safe}}</p> <!-- blog_post.body|safe : Pemite que el body interprete codigos html por ejemplo si que hace el blog usa <p></p> el django lo va a interpretar -->
			 	</div>
			 	<div class="card-footer text-muted">
			 		Update on {{blog_post.date_updated}} by {{blog_post.author}}
			 	</div>
			 </div>


		<!-- End Blog Post -->
	</div>
</div>

{% endblock content %}